### ISSUE TITLE
Working on 4D 17 R6 (64 bits) on Drivers 32 bits - WINDOWS

### ISSUE THREAD

**Issue by AlfonsoIdem** [miyako/4d-plugin-twain-v2#1]
Hi Miyako,

Could be possible that you plugin-twain works wit 4D 64 bits (Windows) but with the scan drivers 32 bits ?

Thanks.

**Comment by miyako** [comment]
that is technically not possible.

you would need a "bridge" application that communicates between 64-bit and 32-bit.

there are commercial solutions for that, which means it's a lot of work.
